services:
  db:
    image: postgres:15.8
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:7.4
    command: --port 5370
    expose:
      - 5370

  app:
    build: .
    env_file:
      - .env
    command: ["bash", "docker/app.sh"]
    ports:
      - 80:80
    depends_on:
      - db
      - redis

  celery:
    build: .
    env_file:
      - .env
    command: ["bash", "docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build: .
    command: ["bash", "docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555